{{- if eq .chezmoi.os "linux" -}}
[".local/bin/cht.sh"]
type = "file"
url = "https://cht.sh/:cht.sh"
executable = true
refreshPeriod = "168h"
{{- end -}}

{{- if eq .de "kde" -}}
[".local/bin/chezmoi_modify_manager"]
type = "archive-file"
url = "https://github.com/VorpalBlade/chezmoi_modify_manager/releases/download/v3.4.0/chezmoi_modify_manager-v3.4.0-x86_64-unknown-linux-gnu.tar.gz"
path = "chezmoi_modify_manager"
executable = true
refreshPeriod = "168h"
{{- end -}}
