[".config/git/alias"]
type = "file"
url = "https://raw.githubusercontent.com/GitAlias/gitalias/main/gitalias.txt"

[".config/git/delta_themes"]
type = "file"
url = "https://raw.githubusercontent.com/dandavison/delta/main/themes.gitconfig"
