"$schema" = "https://starship.rs/config-schema.json"

format = """
$hostname\
$container\
$directory\
$git_status\
$git_branch\
$golang\
$nodejs\
$python\
$cmd_duration\
$line_break\
$character"""

[hostname]
format = "[](fg:green)[](fg:black bg:prev_fg)[](fg:prev_bg bg:bright-black)[ $hostname](bg:prev_bg)[](fg:prev_bg)[─](fg:bright-black)"

[container]
symbol = " "
format = "[](fg:green)[$symbol](fg:black bg:prev_fg)[](fg:prev_bg bg:bright-black)[ $name](bg:prev_bg)[](fg:prev_bg)[─](fg:bright-black)"

[directory]
format = "[](fg:blue)[ ](fg:black bg:prev_fg)[](fg:prev_bg bg:bright-black)[ $read_only$path](bg:prev_bg)[](fg:prev_bg)"
repo_root_style = "fg:bright-black" # Not actually used, but needed to get repo_root_format
repo_root_format = "[](fg:blue)[ ](fg:black bg:prev_fg)[](fg:prev_bg bg:bright-black)[ $repo_root$path](bg:prev_bg)"
truncation_length = 3 # Number of folders that the directory should truncate to
truncate_to_repo = true
truncation_symbol = "…/"
read_only = " "

[git_status]
format = "[$all_status$ahead_behind](fg:red bg:bright-black)[](fg:prev_bg)"
conflicted = " ="
up_to_date = ""
untracked = " ?${count}"
stashed = " $"
modified = " !${count}"
staged = " +"
renamed = " »"
deleted = " ✘"
ahead = " ⇡${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
behind = " ⇣${count}"

[git_branch]
symbol = " "
format = "[─](fg:bright-black)[](fg:cyan)[$symbol](fg:black bg:prev_fg)[](fg:prev_bg bg:bright-black)[ $branch(:$remote-branch)](bg:prev_bg)[](fg:prev_bg)"
ignore_branches = ["main", "master"]

[golang]
format = "[─](fg:bright-black)[](fg:cyan)[$symbol](fg:black bg:prev_fg)[](fg:prev_bg bg:bright-black)[ $version](bg:prev_bg)[](fg:prev_bg)"
symbol = "󰟓 "

[nodejs]
format = "[─](fg:bright-black)[](fg:green)[$symbol](fg:black bg:prev_fg)[](fg:prev_bg bg:bright-black)[ $version](bg:prev_bg)[](fg:prev_bg)"

[python]
format = "[─](fg:bright-black)[](fg:yellow)[$symbol](fg:black bg:prev_fg)[](fg:prev_bg bg:bright-black)[ $version( via $virtualenv)](bg:prev_bg)[](fg:prev_bg)"
symbol = " "

[cmd_duration]
format = "[─](fg:bright-black)[](fg:yellow)[󱎫 ](fg:black bg:prev_fg)[](fg:prev_bg bg:bright-black)[ $duration](bg:prev_bg)[](fg:prev_bg)"

[character]
success_symbol = "[λ](purple)"
error_symbol = "[λ](red)"
vimcmd_symbol = "[λ](green)"
