theme = "gruvbox"

[editor]
bufferline = "multiple"
line-number = "relative"
scrolloff = 10
cursorline = true
color-modes = true

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "diagnostics", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["selections", "file-type", "position-percentage", "total-line-numbers"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
