theme = "gruvbox"

[editor]
bufferline = "multiple"
line-number = "relative"
scrolloff = 10
cursorline = true
color-modes = true

[editor.statusline]
left = ["mode", "diagnostics", "spinner", "version-control"]
center = ["file-name", "file-modification-indicator"]
right = ["selections", "file-type", "position-percentage", "total-line-numbers"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1
