[packages]
apt = [
  "bat",
  "build-essential", # for rust to build
  "cmake",           # for rust to build
  "fzf",
  "ripgrep",
  "ugrep",
  "zoxide",
]

brew = [
  "atuin",
  "bat",
  "bat-extras",
  "binutils",
  "chafa",
  "eza",
  "difftastic",
  "fd",
  "fzf",
  "gh",
  "go",
  "git-interactive-rebase-tool",
  "helix",
  "lazygit",
  "neovim",
  "rclone",
  "ripgrep",
  "sd",
  "shellcheck",
  "shfmt",
  "sevenzip",
  "starship",
  "syncthing",
  "tealdeer",
  "thefuck",
  "taplo",
  "trash-cli",
  "ugrep",
  "uv",
  "yaml-language-server",
  "yq",
  "zoxide",
]

cargo = ["difftastic", "eza", "fd-find", "sd", "starship", "tealdeer"]

flatpak = [
  "org.bleachbit.BleachBit",
  "org.blender.Blender",
  "com.usebottles.bottles",
  "page.kramo.Cartridges",
  "be.alexandervanhee.gradia",
  "org.localsend.localsend_app",
  "md.obsidian.Obsidian",
  "org.signal.Signal",
  "org.telegram.desktop",
  "app.zen_browser.zen",
]

go = ["github.com/Achno/gowall@latest"]

node = [
  "bash-language-server",
  "dockerfile-language-server-nodejs",
  "@microsoft/compose-language-service",
  "markdown-lint",
  "marksman",
  "pyright",
  "vscode-langservers-extracted",
]

pi = ["bat", "cmake", "fzf", "ripgrep", "ugrep", "zoxide"]

python = ["basedpyright", "ruff"]

termux = [
  "bat",
  "eza",
  "fd",
  "fzf",
  "gh",
  "lazygit",
  "neovim",
  "ripgrep",
  "tealdeer",
  "ugrep",
  "yq",
  "zoxide",
]
