[packages]
apt = [
  "bat",
  "build-essential", # for rust to build
  "cmake",           # for rust to build
  "fzf",
  "ripgrep",
  "ugrep",
  "zoxide",
]

brew = [
  "atuin",                # shell history search
  "bat",                  # colorful cat
  "bat-extras",           # bat manpages and more
  "binutils",             # compiler tools
  "chafa",                # image preview in terminal
  "eza",                  # better ls
  "difftastic",           # diffs
  "dust",                 # better du
  "fd",                   # better find
  "fzf",                  # fuzzy finder
  "gh",                   # github cli
  "go",                   # golang
  "helix",                # editor
  "lazygit",              # git tui
  "neovim",               # editor
  "rclone",               # manage cloud storage
  "ripgrep",              # better grep
  "sd",                   # better sed
  "shellcheck",           # bash linter
  "shfmt",                # bash formatter
  "sevenzip",             # archiver
  "starship",             # prompt
  "syncthing",            # sync files
  "tealdeer",             # tldr pages
  "thefuck",              # command correction
  "taplo",                # toml lsp
  "trash-cli",            # trash manager
  "ugrep",                # drop-in better grep for scripts
  "uv",                   # python manager
  "yaml-language-server", # says on the tin
  "yq",                   # jq for yaml
  "zoxide",               # directory jumper
]

cargo = ["difftastic", "eza", "fd-find", "sd", "starship", "tealdeer"]

flatpak = [
  "org.bleachbit.BleachBit",
  "org.blender.Blender",
  "com.usebottles.bottles",
  "page.kramo.Cartridges",
  "be.alexandervanhee.gradia",
  "org.localsend.localsend_app",
  "md.obsidian.Obsidian",
  "org.signal.Signal",
  "org.telegram.desktop",
  "app.zen_browser.zen",
]

go = ["github.com/Achno/gowall@latest"]

node = [
  "bash-language-server",
  "dockerfile-language-server-nodejs",
  "@microsoft/compose-language-service",
  "markdown-lint",
  "marksman",
  "pyright",
  "vscode-langservers-extracted",
]

pi = ["bat", "cmake", "fzf", "ripgrep", "ugrep", "zoxide"]

python = ["basedpyright", "ruff"]

termux = [
  "bat",
  "eza",
  "fd",
  "fzf",
  "gh",
  "lazygit",
  "neovim",
  "ripgrep",
  "tealdeer",
  "ugrep",
  "yq",
  "zoxide",
]
