[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = ["fd", "bat", "chezmoi"]

[source]
command = "fd -t f . (chezmoi source-path)"

[preview]
command = "bat -n --color=always '{}'"
